name: mamabond
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
   
  supabase_flutter: ^2.5.0
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png
    - assets/logo.notext.png
    - assets/milkbank.png
    - assets/profile.png
    - assets/textlogo.png
    - assets/healthcenter.png
    - assets/bfstation.png 

flutter_native_splash:
  background_image: assets/background.png
  android: true
  ios: true
